source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BXLoadMoreControl_Example' do
  pod "BXLoadMoreControl", :path => "../"
end

target 'BXLoadMoreControl_Tests' do
  pod "BXLoadMoreControl", :path => "../"

  
end
