source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BXLoadMoreControl_Example', :exclusive => true do
  pod "BXLoadMoreControl", :path => "../"
end

target 'BXLoadMoreControl_Tests', :exclusive => true do
  pod "BXLoadMoreControl", :path => "../"

  
end
